---
title: "Main Data Analysis"
author: "Yangyang Chen"
date: "`r Sys.Date()`"
output: github_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(viridis)
library(modelr)
library(mgcv)
library(latex2exp)
library(writexl)
library(dplyr)
library(tidymodels)
library(randomForest)
library(caret)
library(ranger)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```
## Data

### Importing dataframe

```{r}
load("C:/Users/auror/OneDrive/桌面/datafest/2024_DataFest/main_data/nhanes_data.rda")
main_df = nhanes_data
df_99 = 
  readxl::read_xlsx("Dietary_data/1999-2000daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_01 = 
  readxl::read_xlsx("Dietary_data/2001-2002daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_03 = 
  readxl::read_xlsx("Dietary_data/2003-2004daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_05 = 
  readxl::read_xlsx("Dietary_data/2005-2006daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_07 = 
  readxl::read_xlsx("Dietary_data/2007-2008daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_09 = 
  readxl::read_xlsx("Dietary_data/2009-2010daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_11 = 
  readxl::read_xlsx("Dietary_data/2011-2012daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_13 = 
  readxl::read_xlsx("Dietary_data/2013-2014daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_15 = 
  readxl::read_xlsx("Dietary_data/2015-2016daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_17 = 
  readxl::read_xlsx("Dietary_data/2017-2020daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)

# Combining Fiber Data
fiber_df =   
  df_99 |> 
  rbind(df_01) |> 
  rbind(df_03) |> 
  rbind(df_05) |> 
  rbind(df_07) |> 
  rbind(df_09) |> 
  rbind(df_11) |> 
  rbind(df_13) |> 
  rbind(df_15) |> 
  rbind(df_17)
```
### Data Cleaning - Filter female data

```{r}
fiber_tidy_df = 
  fiber_df |> 
  janitor::clean_names() |> 
  rename(
    svy_id = seqn,
    svy_year = year
         ) 

# Combining main data and fiber data, and remove NA
df = 
  left_join(fiber_tidy_df, main_df) |> 
  drop_na()
```
```{r}
# Determine the BP as our dependent variable --> create a new binary column called bp: uncontrolled(0): SBP > 140 or DBP > 90 and controlled(1): SBP < 140 and DBP < 90. 
df_with_bp <-
  df %>%
  mutate(bp = ifelse(bp_sys_mean < 140 & bp_dia_mean < 90, "controlled", "uncontrolled"))
# remove the unnecessary bp columns
df_with_bp_2 <-
  df_with_bp %>% 
  select(-contains('bp_'))%>%
  relocate(bp, .after = svy_year)
```
## Exploratory Data Analysis
```{r}
# Remove unnecessary data
data <- 
  df_with_bp_2 %>%
  select(-c(svy_id,svy_year,svy_subpop_htn,svy_subpop_chol,demo_age_years))%>%
  mutate(bp = factor(bp))
# Factor all the categorical data
is.fact <- sapply(data, is.factor)
data_categroies <- 
  data[, is.fact]%>%
  mutate_all(~factor(.))
data_categroies
# A dataframe with all numerical data in data
data_numerical <- 
  select_if(data, is.numeric)
data_numerical
#Combine categorical data and numerical data frame
data_final = cbind(data_numerical, data_categroies)
```


```{r}
index = caret::createDataPartition(data_final$bp,p=0.7,list = FALSE)
train_df = data_final[index, ]
test_df = data_final[-index, ]
#randomForest_model = ranger(formula = bp ~ ., data = train_df)
#randomForest_model = train(bp~., 
 #                data = train_df, 
 #               method = "ranger")
randomForest_model = randomForest(bp~.,data= train_df,importance=TRUE, ntree=300)
```
```{r}
prediction = predict(randomForest_model,test_df)
confustion_matrix = table(prediction, test_df$bp)
accuracy = sum(diag(confustion_matrix))/sum(confustion_matrix)
cat("Accuracy",accuracy,"\n")
confustion_matrix %>%
  knitr::kable(caption="Confusion Matrix of randomForest")
```

```{r}
importance = varImp(randomForest_model)
varImpPlot(randomForest_model, main = "The Gini Coefficient of the RF")
```


### Survey variables
```{r}

```

