---
title: "Main Data Analysis"
author: "Yangyang Chen"
date: "`r Sys.Date()`"
output: github_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(viridis)
library(modelr)
library(mgcv)
library(latex2exp)
library(broom)
library(ggplot2)
library(dplyr)
library(summarytools)
library(writexl)
library(tidymodels)
library(randomForest)
library(caret)
library(ranger)
library(stargazer)
library(ROCR)


knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```
## Data

### Importing dataframe

```{r}
load("~/Desktop/2024_DataFest/main_data/nhanes_data.rda")
main_df = nhanes_data
df_99 = 
  readxl::read_xlsx("Dietary_data/1999-2000daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_01 = 
  readxl::read_xlsx("Dietary_data/2001-2002daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_03 = 
  readxl::read_xlsx("Dietary_data/2003-2004daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_05 = 
  readxl::read_xlsx("Dietary_data/2005-2006daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_07 = 
  readxl::read_xlsx("Dietary_data/2007-2008daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_09 = 
  readxl::read_xlsx("Dietary_data/2009-2010daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_11 = 
  readxl::read_xlsx("Dietary_data/2011-2012daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_13 = 
  readxl::read_xlsx("Dietary_data/2013-2014daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_15 = 
  readxl::read_xlsx("Dietary_data/2015-2016daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)
df_17 = 
  readxl::read_xlsx("Dietary_data/2017-2020daysmean.xlsx") |> 
  rename(MEAN_FIBER = DR_MEAN) |> 
  select(SEQN, MEAN_FIBER, YEAR)

# Combining Fiber Data
fiber_df =   
  df_99 |> 
  rbind(df_01) |> 
  rbind(df_03) |> 
  rbind(df_05) |> 
  rbind(df_07) |> 
  rbind(df_09) |> 
  rbind(df_11) |> 
  rbind(df_13) |> 
  rbind(df_15) |> 
  rbind(df_17)
```
### Data Cleaning

```{r}
fiber_tidy_df = 
  fiber_df |> 
  janitor::clean_names() |> 
  rename(
    svy_id = seqn,
    svy_year = year
         ) 

# Combining main data and fiber data, and remove NA
df = 
  left_join(fiber_tidy_df, main_df) |> 
  drop_na()

# Determine the BP as our dependent variable --> create a new binary column called bp: uncontrolled(0): SBP > 140 or DBP > 90 and controlled(1): SBP < 140 and DBP < 90. 
df_with_bp <-
  df %>%
  mutate(bp = ifelse(bp_sys_mean < 140 & bp_dia_mean < 90, "controlled", "uncontrolled"))
# remove the unnecessary bp columns
df_with_bp_2 <-
  df_with_bp %>% 
  select(-contains('bp_'))%>%
  relocate(bp, .after = svy_year)
```

## Exploratory Data Analysis

```{r}
table_gender = 
df_with_bp_2 %>%
  group_by(demo_gender) %>%
  summarise(
    Count = n(), # total number of entries for each gender
    Controlled = sum(bp == "controlled"), # number of outcomes with value 0
    Uncontrolled = sum(bp == "uncontrolled"), # number of outcomes with value 1
    Percentage = Controlled/Count
  ) %>%
  knitr::kable(digits = 3)  
```

```{r}
# Define age intervals
age_breaks <- c(-Inf, 18, 45, 65, 75, Inf)
age_labels <- c("Under 18",'18-44', '45-64', '65-74', 'Over 75')

# Create age groups and summarize outcomes
df_with_bp_2 %>%
  mutate(Age_group = cut(demo_age_years, breaks = age_breaks, labels = age_labels, right = FALSE)) %>%
  group_by(demo_age_cat) %>%
  summarise(Count = n(),
            Controlled = sum(bp == "controlled", na.rm = TRUE),
            Uncontrolled = sum(bp == "uncontrolled", na.rm = TRUE),
            Percentage = Controlled/(Controlled + Uncontrolled)) %>%
  knitr::kable(digits = 3)  

# Summary statistics
data_summary <- dfSummary(df)

# Histogram of mean_fiber
ggplot(df, aes(x = mean_fiber)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Distribution of Mean Fiber", x = "Mean Fiber", y = "Frequency")

# Boxplot of mean_fiber by demo_race
ggplot(df, aes(x = demo_race, y = mean_fiber, fill = demo_race)) +
  geom_boxplot() +
  labs(title = "Boxplot of Mean Fiber by Race", x = "Race", y = "Mean Fiber")

# Scatter plot of bp_sys_mean vs bp_dia_mean
ggplot(df, aes(x = bp_sys_mean, y = bp_dia_mean, color = demo_race)) +
  geom_point() +
  labs(title = "Scatter Plot of Systolic vs Diastolic Blood Pressure",
       x = "Systolic Blood Pressure", y = "Diastolic Blood Pressure")

df %>%
  ggplot(aes(x = bp_sys_mean, fill = demo_race)) +
  geom_density(alpha = 0.7) +
  labs(title = "Grouped Density Plot of Systolic Blood Pressure by Race", x = "Systolic Blood Pressure") +
  theme_minimal()

df %>%
  ggplot(aes(x = bp_sys_mean)) +
  geom_histogram(binwidth = 5, fill = "lightblue", color = "black", alpha = 0.7) +
  geom_density(color = "darkred", size = 1) +
  labs(title = "Histogram with Density Plot of Systolic Blood Pressure", x = "Systolic Blood Pressure") +
  theme_minimal()
```

## Random Forests
```{r}
# Remove unnecessary data
data <- 
  df_with_bp_2 %>%
  select(-c(svy_id,svy_year,svy_subpop_htn,svy_subpop_chol,demo_age_years))%>%
  mutate(bp = factor(bp))
# Factor all the categorical data
is.fact <- sapply(data, is.factor)
data_categroies <- 
  data[, is.fact]%>%
  mutate_all(~factor(.))
data_categroies
# A dataframe with all numerical data in data
data_numerical <- 
  select_if(data, is.numeric)
data_numerical
#Combine categorical data and numerical data frame
data_final = cbind(data_numerical, data_categroies)
```


```{r}
index = caret::createDataPartition(data_final$bp,p=0.7,list = FALSE)
train_df = data_final[index, ]
test_df = data_final[-index, ]
#randomForest_model = ranger(formula = bp ~ ., data = train_df)
#randomForest_model = train(bp~., 
 #                data = train_df, 
 #               method = "ranger")
randomForest_model = randomForest(bp~.,data= train_df,importance=TRUE, ntree=300)
```
```{r}
prediction = predict(randomForest_model,test_df)
confustion_matrix = table(prediction, test_df$bp)
accuracy = sum(diag(confustion_matrix))/sum(confustion_matrix)
cat("Accuracy",accuracy,"\n")
confustion_matrix %>%
  knitr::kable(caption="Confusion Matrix of randomForest")
```

```{r}
importance = varImp(randomForest_model)
varImpPlot(randomForest_model, main = "The Gini Coefficient of the RF")
```

### Logistics Regression

```{r}
convert_to_factor <- function(df, columns) {
  df[columns] <- lapply(df[columns], factor)
  return(df)
}

df_tidy = 
  df_with_bp_2 |>
  convert_to_factor(c("bp", "demo_age_cat", "demo_race", "demo_race_black", "demo_pregnant", "demo_gender", "htn_jnc7",	"htn_accaha",	"htn_escesh",	"htn_aware",	"htn_resistant_jnc7",	"htn_resistant_accaha",	"htn_resistant_jnc7_thz",	"htn_resistant_accaha_thz",	"chol_measured_never",	"chol_measured_last", "chol_total_gteq_200",	"chol_total_gteq_240", "chol_hdl_low", "chol_trig_gteq_150", "chol_ldl_5cat",	"chol_ldl_lt_70",	"chol_ldl_gteq_70",	"chol_ldl_lt_100",	"chol_ldl_gteq_100",	"chol_ldl_gteq_190",	"chol_ldl_persistent", "chol_nonhdl_5cat",	"chol_nonhdl_lt_100",	"chol_nonhdl_gteq_100",	"chol_nonhdl_gteq_220",	"chol_med_use",	"chol_med_use_sr",	"chol_med_statin",	"chol_med_ezetimibe",	"chol_med_pcsk9i",	"chol_med_bile",	"chol_med_fibric_acid",	"chol_med_atorvastatin", 	"chol_med_simvastatin",	"chol_med_rosuvastatin",	"chol_med_pravastatin",	"chol_med_pitavastatin",	"chol_med_fluvastatin",	"chol_med_lovastatin",	"chol_med_other",	"chol_med_addon_use",	"chol_med_addon_recommended_ahaacc",	"chol_med_statin_recommended_ahaacc",	"chol_med_recommended_ever",	"ascvd_risk_vh_ahaacc",	"cc_smoke",	"cc_bmi",	"cc_diabetes",	"cc_ckd",	"cc_cvd_mi",	"cc_cvd_chd",	"cc_cvd_stroke",	"cc_cvd_ascvd",	"cc_cvd_hf",	"cc_cvd_any"))

df_tidy = 
  df_tidy |> 
  select(-c(svy_year,svy_id, svy_subpop_htn, svy_subpop_chol, demo_race_black, htn_escesh, chol_ldl_lt_70, chol_ldl_gteq_70, chol_ldl_lt_100, chol_ldl_gteq_100, chol_ldl_gteq_190, chol_nonhdl, chol_nonhdl_lt_100, chol_nonhdl_gteq_100, chol_nonhdl_gteq_220)) 
glm_complete = glm(bp ~ ., data = df_tidy, family = binomial(link = logit))
stepwise_complete = stats::step(glm_complete)

table_step = 
stepwise_complete |>
  broom::tidy() |>
  select(term, estimate, p.value) |>
  arrange(desc(p.value)) |> 
  knitr::kable(
    caption = "Estimate and P-value of Generalized Linear Model Using All Patients Data", 
    col.names = c("Predictor", "Estimate", "P-value"),
    digits = 3
  ) |>
    kableExtra::kable_styling(
    "basic",
    full_width = FALSE,
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    position = "center", 
    font_size = 16, 
    latex_options = c("hold_position")
  )
table_step

##ROC Curve
logistics_validation =
  df_tidy |>
  filter(demo_age_cat == "45 to 64")
predict = predict(stepwise_complete, newdata = logistics_validation, type = "response")
pred = prediction(predictions = predict, labels = logistics_validation$bp)
roc = performance(pred, "tpr", "fpr")
auc = performance(pred, measure = "auc")@y.values[[1]]

plot(roc, colorize = F)
title(main = "The ROC Curve of Generalized Linear Model")
```





